"""add level to activities

Revision ID: 2ff9afdda58d
Revises: 8d0a0d35d01b
Create Date: 2026-01-16 17:39:13.514163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff9afdda58d'
down_revision: Union[str, Sequence[str], None] = '8d0a0d35d01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'level')
    # ### end Alembic commands ###
